/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LayoutRouteImport } from "./routes/_layout"
import { Route as WorkspaceIdRouteImport } from "./routes/$workspaceId"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as WorkspaceIdIndexRouteImport } from "./routes/$workspaceId/index"
import { Route as StripeCallbackRouteImport } from "./routes/stripe/callback"
import { Route as EmbedSlugRouteImport } from "./routes/embed.$slug"
import { Route as AdvertiseSuccessRouteImport } from "./routes/advertise/success"
import { Route as AdvertiseCancelledRouteImport } from "./routes/advertise/cancelled"
import { Route as LayoutOnboardingRouteImport } from "./routes/_layout.onboarding"
import { Route as LayoutLoginRouteImport } from "./routes/_layout.login"
import { Route as WorkspaceIdEmbedRouteImport } from "./routes/$workspaceId/embed"
import { Route as LayoutOnboardingIndexRouteImport } from "./routes/_layout.onboarding.index"
import { Route as WorkspaceIdTiersIndexRouteImport } from "./routes/$workspaceId/tiers/index"
import { Route as WorkspaceIdSettingsIndexRouteImport } from "./routes/$workspaceId/settings/index"
import { Route as WorkspaceIdFieldsIndexRouteImport } from "./routes/$workspaceId/fields/index"
import { Route as WorkspaceIdAdvertisersIndexRouteImport } from "./routes/$workspaceId/advertisers/index"
import { Route as WorkspaceIdAdsIndexRouteImport } from "./routes/$workspaceId/ads/index"
import { Route as WorkspaceIdAccountIndexRouteImport } from "./routes/$workspaceId/account/index"
import { Route as LayoutOnboardingStepRouteImport } from "./routes/_layout.onboarding.$step"
import { Route as WorkspaceIdTiersNewRouteImport } from "./routes/$workspaceId/tiers/new"
import { Route as WorkspaceIdTiersTierIdRouteImport } from "./routes/$workspaceId/tiers/$tierId"
import { Route as WorkspaceIdFieldsNewRouteImport } from "./routes/$workspaceId/fields/new"
import { Route as WorkspaceIdFieldsFieldIdRouteImport } from "./routes/$workspaceId/fields/$fieldId"
import { Route as WorkspaceIdAdvertisersAdvertiserIdRouteImport } from "./routes/$workspaceId/advertisers/$advertiserId"
import { Route as WorkspaceIdAdsAdIdRouteImport } from "./routes/$workspaceId/ads/$adId"
import { Route as WorkspaceIdSettingsGeneralIndexRouteImport } from "./routes/$workspaceId/settings/general/index"

const LayoutRoute = LayoutRouteImport.update({
  id: "/_layout",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: "/$workspaceId",
  path: "/$workspaceId",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdIndexRoute = WorkspaceIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const StripeCallbackRoute = StripeCallbackRouteImport.update({
  id: "/stripe/callback",
  path: "/stripe/callback",
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedSlugRoute = EmbedSlugRouteImport.update({
  id: "/embed/$slug",
  path: "/embed/$slug",
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseSuccessRoute = AdvertiseSuccessRouteImport.update({
  id: "/advertise/success",
  path: "/advertise/success",
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseCancelledRoute = AdvertiseCancelledRouteImport.update({
  id: "/advertise/cancelled",
  path: "/advertise/cancelled",
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutOnboardingRoute = LayoutOnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => LayoutRoute,
} as any)
const WorkspaceIdEmbedRoute = WorkspaceIdEmbedRouteImport.update({
  id: "/embed",
  path: "/embed",
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const LayoutOnboardingIndexRoute = LayoutOnboardingIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutOnboardingRoute,
} as any)
const WorkspaceIdTiersIndexRoute = WorkspaceIdTiersIndexRouteImport.update({
  id: "/tiers/",
  path: "/tiers/",
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdSettingsIndexRoute =
  WorkspaceIdSettingsIndexRouteImport.update({
    id: "/settings/",
    path: "/settings/",
    getParentRoute: () => WorkspaceIdRoute,
  } as any)
const WorkspaceIdFieldsIndexRoute = WorkspaceIdFieldsIndexRouteImport.update({
  id: "/fields/",
  path: "/fields/",
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdAdvertisersIndexRoute =
  WorkspaceIdAdvertisersIndexRouteImport.update({
    id: "/advertisers/",
    path: "/advertisers/",
    getParentRoute: () => WorkspaceIdRoute,
  } as any)
const WorkspaceIdAdsIndexRoute = WorkspaceIdAdsIndexRouteImport.update({
  id: "/ads/",
  path: "/ads/",
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdAccountIndexRoute = WorkspaceIdAccountIndexRouteImport.update({
  id: "/account/",
  path: "/account/",
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const LayoutOnboardingStepRoute = LayoutOnboardingStepRouteImport.update({
  id: "/$step",
  path: "/$step",
  getParentRoute: () => LayoutOnboardingRoute,
} as any)
const WorkspaceIdTiersNewRoute = WorkspaceIdTiersNewRouteImport.update({
  id: "/tiers/new",
  path: "/tiers/new",
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdTiersTierIdRoute = WorkspaceIdTiersTierIdRouteImport.update({
  id: "/tiers/$tierId",
  path: "/tiers/$tierId",
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdFieldsNewRoute = WorkspaceIdFieldsNewRouteImport.update({
  id: "/fields/new",
  path: "/fields/new",
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdFieldsFieldIdRoute =
  WorkspaceIdFieldsFieldIdRouteImport.update({
    id: "/fields/$fieldId",
    path: "/fields/$fieldId",
    getParentRoute: () => WorkspaceIdRoute,
  } as any)
const WorkspaceIdAdvertisersAdvertiserIdRoute =
  WorkspaceIdAdvertisersAdvertiserIdRouteImport.update({
    id: "/advertisers/$advertiserId",
    path: "/advertisers/$advertiserId",
    getParentRoute: () => WorkspaceIdRoute,
  } as any)
const WorkspaceIdAdsAdIdRoute = WorkspaceIdAdsAdIdRouteImport.update({
  id: "/ads/$adId",
  path: "/ads/$adId",
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdSettingsGeneralIndexRoute =
  WorkspaceIdSettingsGeneralIndexRouteImport.update({
    id: "/settings/general/",
    path: "/settings/general/",
    getParentRoute: () => WorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/$workspaceId": typeof WorkspaceIdRouteWithChildren
  "/$workspaceId/embed": typeof WorkspaceIdEmbedRoute
  "/login": typeof LayoutLoginRoute
  "/onboarding": typeof LayoutOnboardingRouteWithChildren
  "/advertise/cancelled": typeof AdvertiseCancelledRoute
  "/advertise/success": typeof AdvertiseSuccessRoute
  "/embed/$slug": typeof EmbedSlugRoute
  "/stripe/callback": typeof StripeCallbackRoute
  "/$workspaceId/": typeof WorkspaceIdIndexRoute
  "/$workspaceId/ads/$adId": typeof WorkspaceIdAdsAdIdRoute
  "/$workspaceId/advertisers/$advertiserId": typeof WorkspaceIdAdvertisersAdvertiserIdRoute
  "/$workspaceId/fields/$fieldId": typeof WorkspaceIdFieldsFieldIdRoute
  "/$workspaceId/fields/new": typeof WorkspaceIdFieldsNewRoute
  "/$workspaceId/tiers/$tierId": typeof WorkspaceIdTiersTierIdRoute
  "/$workspaceId/tiers/new": typeof WorkspaceIdTiersNewRoute
  "/onboarding/$step": typeof LayoutOnboardingStepRoute
  "/$workspaceId/account/": typeof WorkspaceIdAccountIndexRoute
  "/$workspaceId/ads/": typeof WorkspaceIdAdsIndexRoute
  "/$workspaceId/advertisers/": typeof WorkspaceIdAdvertisersIndexRoute
  "/$workspaceId/fields/": typeof WorkspaceIdFieldsIndexRoute
  "/$workspaceId/settings/": typeof WorkspaceIdSettingsIndexRoute
  "/$workspaceId/tiers/": typeof WorkspaceIdTiersIndexRoute
  "/onboarding/": typeof LayoutOnboardingIndexRoute
  "/$workspaceId/settings/general/": typeof WorkspaceIdSettingsGeneralIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/$workspaceId/embed": typeof WorkspaceIdEmbedRoute
  "/login": typeof LayoutLoginRoute
  "/advertise/cancelled": typeof AdvertiseCancelledRoute
  "/advertise/success": typeof AdvertiseSuccessRoute
  "/embed/$slug": typeof EmbedSlugRoute
  "/stripe/callback": typeof StripeCallbackRoute
  "/$workspaceId": typeof WorkspaceIdIndexRoute
  "/$workspaceId/ads/$adId": typeof WorkspaceIdAdsAdIdRoute
  "/$workspaceId/advertisers/$advertiserId": typeof WorkspaceIdAdvertisersAdvertiserIdRoute
  "/$workspaceId/fields/$fieldId": typeof WorkspaceIdFieldsFieldIdRoute
  "/$workspaceId/fields/new": typeof WorkspaceIdFieldsNewRoute
  "/$workspaceId/tiers/$tierId": typeof WorkspaceIdTiersTierIdRoute
  "/$workspaceId/tiers/new": typeof WorkspaceIdTiersNewRoute
  "/onboarding/$step": typeof LayoutOnboardingStepRoute
  "/$workspaceId/account": typeof WorkspaceIdAccountIndexRoute
  "/$workspaceId/ads": typeof WorkspaceIdAdsIndexRoute
  "/$workspaceId/advertisers": typeof WorkspaceIdAdvertisersIndexRoute
  "/$workspaceId/fields": typeof WorkspaceIdFieldsIndexRoute
  "/$workspaceId/settings": typeof WorkspaceIdSettingsIndexRoute
  "/$workspaceId/tiers": typeof WorkspaceIdTiersIndexRoute
  "/onboarding": typeof LayoutOnboardingIndexRoute
  "/$workspaceId/settings/general": typeof WorkspaceIdSettingsGeneralIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/$workspaceId": typeof WorkspaceIdRouteWithChildren
  "/_layout": typeof LayoutRouteWithChildren
  "/$workspaceId/embed": typeof WorkspaceIdEmbedRoute
  "/_layout/login": typeof LayoutLoginRoute
  "/_layout/onboarding": typeof LayoutOnboardingRouteWithChildren
  "/advertise/cancelled": typeof AdvertiseCancelledRoute
  "/advertise/success": typeof AdvertiseSuccessRoute
  "/embed/$slug": typeof EmbedSlugRoute
  "/stripe/callback": typeof StripeCallbackRoute
  "/$workspaceId/": typeof WorkspaceIdIndexRoute
  "/$workspaceId/ads/$adId": typeof WorkspaceIdAdsAdIdRoute
  "/$workspaceId/advertisers/$advertiserId": typeof WorkspaceIdAdvertisersAdvertiserIdRoute
  "/$workspaceId/fields/$fieldId": typeof WorkspaceIdFieldsFieldIdRoute
  "/$workspaceId/fields/new": typeof WorkspaceIdFieldsNewRoute
  "/$workspaceId/tiers/$tierId": typeof WorkspaceIdTiersTierIdRoute
  "/$workspaceId/tiers/new": typeof WorkspaceIdTiersNewRoute
  "/_layout/onboarding/$step": typeof LayoutOnboardingStepRoute
  "/$workspaceId/account/": typeof WorkspaceIdAccountIndexRoute
  "/$workspaceId/ads/": typeof WorkspaceIdAdsIndexRoute
  "/$workspaceId/advertisers/": typeof WorkspaceIdAdvertisersIndexRoute
  "/$workspaceId/fields/": typeof WorkspaceIdFieldsIndexRoute
  "/$workspaceId/settings/": typeof WorkspaceIdSettingsIndexRoute
  "/$workspaceId/tiers/": typeof WorkspaceIdTiersIndexRoute
  "/_layout/onboarding/": typeof LayoutOnboardingIndexRoute
  "/$workspaceId/settings/general/": typeof WorkspaceIdSettingsGeneralIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/$workspaceId"
    | "/$workspaceId/embed"
    | "/login"
    | "/onboarding"
    | "/advertise/cancelled"
    | "/advertise/success"
    | "/embed/$slug"
    | "/stripe/callback"
    | "/$workspaceId/"
    | "/$workspaceId/ads/$adId"
    | "/$workspaceId/advertisers/$advertiserId"
    | "/$workspaceId/fields/$fieldId"
    | "/$workspaceId/fields/new"
    | "/$workspaceId/tiers/$tierId"
    | "/$workspaceId/tiers/new"
    | "/onboarding/$step"
    | "/$workspaceId/account/"
    | "/$workspaceId/ads/"
    | "/$workspaceId/advertisers/"
    | "/$workspaceId/fields/"
    | "/$workspaceId/settings/"
    | "/$workspaceId/tiers/"
    | "/onboarding/"
    | "/$workspaceId/settings/general/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/$workspaceId/embed"
    | "/login"
    | "/advertise/cancelled"
    | "/advertise/success"
    | "/embed/$slug"
    | "/stripe/callback"
    | "/$workspaceId"
    | "/$workspaceId/ads/$adId"
    | "/$workspaceId/advertisers/$advertiserId"
    | "/$workspaceId/fields/$fieldId"
    | "/$workspaceId/fields/new"
    | "/$workspaceId/tiers/$tierId"
    | "/$workspaceId/tiers/new"
    | "/onboarding/$step"
    | "/$workspaceId/account"
    | "/$workspaceId/ads"
    | "/$workspaceId/advertisers"
    | "/$workspaceId/fields"
    | "/$workspaceId/settings"
    | "/$workspaceId/tiers"
    | "/onboarding"
    | "/$workspaceId/settings/general"
  id:
    | "__root__"
    | "/"
    | "/$workspaceId"
    | "/_layout"
    | "/$workspaceId/embed"
    | "/_layout/login"
    | "/_layout/onboarding"
    | "/advertise/cancelled"
    | "/advertise/success"
    | "/embed/$slug"
    | "/stripe/callback"
    | "/$workspaceId/"
    | "/$workspaceId/ads/$adId"
    | "/$workspaceId/advertisers/$advertiserId"
    | "/$workspaceId/fields/$fieldId"
    | "/$workspaceId/fields/new"
    | "/$workspaceId/tiers/$tierId"
    | "/$workspaceId/tiers/new"
    | "/_layout/onboarding/$step"
    | "/$workspaceId/account/"
    | "/$workspaceId/ads/"
    | "/$workspaceId/advertisers/"
    | "/$workspaceId/fields/"
    | "/$workspaceId/settings/"
    | "/$workspaceId/tiers/"
    | "/_layout/onboarding/"
    | "/$workspaceId/settings/general/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceIdRoute: typeof WorkspaceIdRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  AdvertiseCancelledRoute: typeof AdvertiseCancelledRoute
  AdvertiseSuccessRoute: typeof AdvertiseSuccessRoute
  EmbedSlugRoute: typeof EmbedSlugRoute
  StripeCallbackRoute: typeof StripeCallbackRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$workspaceId": {
      id: "/$workspaceId"
      path: "/$workspaceId"
      fullPath: "/$workspaceId"
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$workspaceId/": {
      id: "/$workspaceId/"
      path: "/"
      fullPath: "/$workspaceId/"
      preLoaderRoute: typeof WorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    "/stripe/callback": {
      id: "/stripe/callback"
      path: "/stripe/callback"
      fullPath: "/stripe/callback"
      preLoaderRoute: typeof StripeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/embed/$slug": {
      id: "/embed/$slug"
      path: "/embed/$slug"
      fullPath: "/embed/$slug"
      preLoaderRoute: typeof EmbedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/advertise/success": {
      id: "/advertise/success"
      path: "/advertise/success"
      fullPath: "/advertise/success"
      preLoaderRoute: typeof AdvertiseSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/advertise/cancelled": {
      id: "/advertise/cancelled"
      path: "/advertise/cancelled"
      fullPath: "/advertise/cancelled"
      preLoaderRoute: typeof AdvertiseCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_layout/onboarding": {
      id: "/_layout/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof LayoutOnboardingRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/login": {
      id: "/_layout/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/$workspaceId/embed": {
      id: "/$workspaceId/embed"
      path: "/embed"
      fullPath: "/$workspaceId/embed"
      preLoaderRoute: typeof WorkspaceIdEmbedRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    "/_layout/onboarding/": {
      id: "/_layout/onboarding/"
      path: "/"
      fullPath: "/onboarding/"
      preLoaderRoute: typeof LayoutOnboardingIndexRouteImport
      parentRoute: typeof LayoutOnboardingRoute
    }
    "/$workspaceId/tiers/": {
      id: "/$workspaceId/tiers/"
      path: "/tiers"
      fullPath: "/$workspaceId/tiers/"
      preLoaderRoute: typeof WorkspaceIdTiersIndexRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    "/$workspaceId/settings/": {
      id: "/$workspaceId/settings/"
      path: "/settings"
      fullPath: "/$workspaceId/settings/"
      preLoaderRoute: typeof WorkspaceIdSettingsIndexRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    "/$workspaceId/fields/": {
      id: "/$workspaceId/fields/"
      path: "/fields"
      fullPath: "/$workspaceId/fields/"
      preLoaderRoute: typeof WorkspaceIdFieldsIndexRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    "/$workspaceId/advertisers/": {
      id: "/$workspaceId/advertisers/"
      path: "/advertisers"
      fullPath: "/$workspaceId/advertisers/"
      preLoaderRoute: typeof WorkspaceIdAdvertisersIndexRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    "/$workspaceId/ads/": {
      id: "/$workspaceId/ads/"
      path: "/ads"
      fullPath: "/$workspaceId/ads/"
      preLoaderRoute: typeof WorkspaceIdAdsIndexRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    "/$workspaceId/account/": {
      id: "/$workspaceId/account/"
      path: "/account"
      fullPath: "/$workspaceId/account/"
      preLoaderRoute: typeof WorkspaceIdAccountIndexRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    "/_layout/onboarding/$step": {
      id: "/_layout/onboarding/$step"
      path: "/$step"
      fullPath: "/onboarding/$step"
      preLoaderRoute: typeof LayoutOnboardingStepRouteImport
      parentRoute: typeof LayoutOnboardingRoute
    }
    "/$workspaceId/tiers/new": {
      id: "/$workspaceId/tiers/new"
      path: "/tiers/new"
      fullPath: "/$workspaceId/tiers/new"
      preLoaderRoute: typeof WorkspaceIdTiersNewRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    "/$workspaceId/tiers/$tierId": {
      id: "/$workspaceId/tiers/$tierId"
      path: "/tiers/$tierId"
      fullPath: "/$workspaceId/tiers/$tierId"
      preLoaderRoute: typeof WorkspaceIdTiersTierIdRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    "/$workspaceId/fields/new": {
      id: "/$workspaceId/fields/new"
      path: "/fields/new"
      fullPath: "/$workspaceId/fields/new"
      preLoaderRoute: typeof WorkspaceIdFieldsNewRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    "/$workspaceId/fields/$fieldId": {
      id: "/$workspaceId/fields/$fieldId"
      path: "/fields/$fieldId"
      fullPath: "/$workspaceId/fields/$fieldId"
      preLoaderRoute: typeof WorkspaceIdFieldsFieldIdRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    "/$workspaceId/advertisers/$advertiserId": {
      id: "/$workspaceId/advertisers/$advertiserId"
      path: "/advertisers/$advertiserId"
      fullPath: "/$workspaceId/advertisers/$advertiserId"
      preLoaderRoute: typeof WorkspaceIdAdvertisersAdvertiserIdRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    "/$workspaceId/ads/$adId": {
      id: "/$workspaceId/ads/$adId"
      path: "/ads/$adId"
      fullPath: "/$workspaceId/ads/$adId"
      preLoaderRoute: typeof WorkspaceIdAdsAdIdRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    "/$workspaceId/settings/general/": {
      id: "/$workspaceId/settings/general/"
      path: "/settings/general"
      fullPath: "/$workspaceId/settings/general/"
      preLoaderRoute: typeof WorkspaceIdSettingsGeneralIndexRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
  }
}

interface WorkspaceIdRouteChildren {
  WorkspaceIdEmbedRoute: typeof WorkspaceIdEmbedRoute
  WorkspaceIdIndexRoute: typeof WorkspaceIdIndexRoute
  WorkspaceIdAdsAdIdRoute: typeof WorkspaceIdAdsAdIdRoute
  WorkspaceIdAdvertisersAdvertiserIdRoute: typeof WorkspaceIdAdvertisersAdvertiserIdRoute
  WorkspaceIdFieldsFieldIdRoute: typeof WorkspaceIdFieldsFieldIdRoute
  WorkspaceIdFieldsNewRoute: typeof WorkspaceIdFieldsNewRoute
  WorkspaceIdTiersTierIdRoute: typeof WorkspaceIdTiersTierIdRoute
  WorkspaceIdTiersNewRoute: typeof WorkspaceIdTiersNewRoute
  WorkspaceIdAccountIndexRoute: typeof WorkspaceIdAccountIndexRoute
  WorkspaceIdAdsIndexRoute: typeof WorkspaceIdAdsIndexRoute
  WorkspaceIdAdvertisersIndexRoute: typeof WorkspaceIdAdvertisersIndexRoute
  WorkspaceIdFieldsIndexRoute: typeof WorkspaceIdFieldsIndexRoute
  WorkspaceIdSettingsIndexRoute: typeof WorkspaceIdSettingsIndexRoute
  WorkspaceIdTiersIndexRoute: typeof WorkspaceIdTiersIndexRoute
  WorkspaceIdSettingsGeneralIndexRoute: typeof WorkspaceIdSettingsGeneralIndexRoute
}

const WorkspaceIdRouteChildren: WorkspaceIdRouteChildren = {
  WorkspaceIdEmbedRoute: WorkspaceIdEmbedRoute,
  WorkspaceIdIndexRoute: WorkspaceIdIndexRoute,
  WorkspaceIdAdsAdIdRoute: WorkspaceIdAdsAdIdRoute,
  WorkspaceIdAdvertisersAdvertiserIdRoute:
    WorkspaceIdAdvertisersAdvertiserIdRoute,
  WorkspaceIdFieldsFieldIdRoute: WorkspaceIdFieldsFieldIdRoute,
  WorkspaceIdFieldsNewRoute: WorkspaceIdFieldsNewRoute,
  WorkspaceIdTiersTierIdRoute: WorkspaceIdTiersTierIdRoute,
  WorkspaceIdTiersNewRoute: WorkspaceIdTiersNewRoute,
  WorkspaceIdAccountIndexRoute: WorkspaceIdAccountIndexRoute,
  WorkspaceIdAdsIndexRoute: WorkspaceIdAdsIndexRoute,
  WorkspaceIdAdvertisersIndexRoute: WorkspaceIdAdvertisersIndexRoute,
  WorkspaceIdFieldsIndexRoute: WorkspaceIdFieldsIndexRoute,
  WorkspaceIdSettingsIndexRoute: WorkspaceIdSettingsIndexRoute,
  WorkspaceIdTiersIndexRoute: WorkspaceIdTiersIndexRoute,
  WorkspaceIdSettingsGeneralIndexRoute: WorkspaceIdSettingsGeneralIndexRoute,
}

const WorkspaceIdRouteWithChildren = WorkspaceIdRoute._addFileChildren(
  WorkspaceIdRouteChildren,
)

interface LayoutOnboardingRouteChildren {
  LayoutOnboardingStepRoute: typeof LayoutOnboardingStepRoute
  LayoutOnboardingIndexRoute: typeof LayoutOnboardingIndexRoute
}

const LayoutOnboardingRouteChildren: LayoutOnboardingRouteChildren = {
  LayoutOnboardingStepRoute: LayoutOnboardingStepRoute,
  LayoutOnboardingIndexRoute: LayoutOnboardingIndexRoute,
}

const LayoutOnboardingRouteWithChildren =
  LayoutOnboardingRoute._addFileChildren(LayoutOnboardingRouteChildren)

interface LayoutRouteChildren {
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutOnboardingRoute: typeof LayoutOnboardingRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutOnboardingRoute: LayoutOnboardingRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceIdRoute: WorkspaceIdRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  AdvertiseCancelledRoute: AdvertiseCancelledRoute,
  AdvertiseSuccessRoute: AdvertiseSuccessRoute,
  EmbedSlugRoute: EmbedSlugRoute,
  StripeCallbackRoute: StripeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
