name = "openads-website"
pages_build_output_dir = "./dist"
compatibility_date = "2026-04-08"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
PLAUSIBLE_DOMAIN = "openads.co"
PLAUSIBLE_URL = "https://p.kulp.in"
