export { createEmailClient, type EmailClient } from "./client"
export { renderTemplate, type RenderResult } from "./render"
export { AdApproved, type AdApprovedProps } from "./templates/ad-approved"
export { AdChangesRequested, type AdChangesRequestedProps } from "./templates/ad-changes-requested"
export { AdPendingReview, type AdPendingReviewProps } from "./templates/ad-pending-review"
export { AdRejected, type AdRejectedProps } from "./templates/ad-rejected"
export type { EmailClientConfig, EmailRecipient, SendEmailInput, UpsertContactInput } from "./types"
